version: '3.8'

services:
  bet-maker:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis-bet
    environment:
      - APP_NAME=Bet Maker Service
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://betmaker:betmaker@127.0.0.1:5432/betmaker
      - REDIS_URL=redis://127.0.0.1:6379
      - LINE_PROVIDER_URL=http://127.0.0.1:8000
      - LINE_PROVIDER_TIMEOUT=5
      - MIN_BET_AMOUNT=1.0
      - MAX_BET_AMOUNT=100000.0
    network_mode: host
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=betmaker
      - POSTGRES_USER=betmaker
      - POSTGRES_PASSWORD=betmaker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U betmaker" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-bet:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: